
Pool shape : torch.Size([40000, 1, 28, 28])
Starting epig acquisition
Using original estimate_epig function
[run_logprobs_acq_epig_marglik_40k.py:191]INFO: Initial test log-likelihood: -3.0136
[run_logprobs_acq_epig_marglik_40k.py:192]INFO: Initial test Bayes log-likelihood: -2.1994
[run_logprobs_acq_epig_marglik_40k.py:193]INFO: Initial accuracy: 52.26%
Traceback (most recent call last):
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_logprobs_acq_epig_marglik_40k.py", line 69, in estimate_epig_minibatch
    f_mu, f_var = m_model._glm_predictive_distribution(combined_inputs)
AttributeError: 'LaplaceActiveLearner' object has no attribute '_glm_predictive_distribution'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_logprobs_acq_epig_marglik_40k.py", line 300, in <module>
    main(**args)
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_logprobs_acq_epig_marglik_40k.py", line 218, in main
    scores = estimate_epig(learner, dataset.get_pool_loader(batch_size=batch_size), target_inputs, cfg.acquisition.epig_using_matmul)
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_logprobs_acq_epig_marglik_40k.py", line 52, in estimate_epig
    epig_scores = estimate_epig_minibatch(m_model, inputs, target_inputs, use_matmul)  # [B,]
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_logprobs_acq_epig_marglik_40k.py", line 74, in estimate_epig_minibatch
    f_mu, f_var = m_model._glm_predictive_distribution(combined_inputs)
AttributeError: 'LaplaceActiveLearner' object has no attribute '_glm_predictive_distribution'
Traceback (most recent call last):
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_logprobs_acq_epig_marglik_40k.py", line 69, in estimate_epig_minibatch
    f_mu, f_var = m_model._glm_predictive_distribution(combined_inputs)
AttributeError: 'LaplaceActiveLearner' object has no attribute '_glm_predictive_distribution'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_logprobs_acq_epig_marglik_40k.py", line 300, in <module>
    main(**args)
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_logprobs_acq_epig_marglik_40k.py", line 218, in main
    scores = estimate_epig(learner, dataset.get_pool_loader(batch_size=batch_size), target_inputs, cfg.acquisition.epig_using_matmul)
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_logprobs_acq_epig_marglik_40k.py", line 52, in estimate_epig
    epig_scores = estimate_epig_minibatch(m_model, inputs, target_inputs, use_matmul)  # [B,]
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_logprobs_acq_epig_marglik_40k.py", line 74, in estimate_epig_minibatch
    f_mu, f_var = m_model._glm_predictive_distribution(combined_inputs)
AttributeError: 'LaplaceActiveLearner' object has no attribute '_glm_predictive_distribution'