
Pool shape : torch.Size([40000, 1, 28, 28])
Traceback (most recent call last):
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_acq_epig_marglik_40k.py", line 304, in <module>
    main(**args)
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_acq_epig_marglik_40k.py", line 190, in main
    test_ll_bayes = learner.log_lik_bayes(test_loader)
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/active_learning/active_learners.py", line 96, in log_lik_bayes
    p = self.la(x, link_approx='mc')
  File "/usr/local/lib/python3.10/dist-packages/laplace/baselaplace.py", line 597, in __call__
    return self.predictive_samples(x, pred_type='glm', n_samples=n_samples,
  File "/usr/local/lib/python3.10/dist-packages/laplace/baselaplace.py", line 660, in predictive_samples
    f_mu, f_var = self._glm_predictive_distribution(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/laplace/baselaplace.py", line 680, in _glm_predictive_distribution
    f_var = self.functional_variance(Js)
  File "/usr/local/lib/python3.10/dist-packages/laplace/baselaplace.py", line 944, in functional_variance
    return self.posterior_precision.inv_square_form(Js)
  File "/usr/local/lib/python3.10/dist-packages/laplace/utils/matrix.py", line 406, in inv_square_form
    SW = self._bmm(W, exponent=-1)
  File "/usr/local/lib/python3.10/dist-packages/laplace/utils/matrix.py", line 396, in _bmm
    W_p = Q1 @ W_p @ Q2.T
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch.
Traceback (most recent call last):
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_acq_epig_marglik_40k.py", line 304, in <module>
    main(**args)
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_acq_epig_marglik_40k.py", line 190, in main
    test_ll_bayes = learner.log_lik_bayes(test_loader)
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/active_learning/active_learners.py", line 96, in log_lik_bayes
    p = self.la(x, link_approx='mc')
  File "/usr/local/lib/python3.10/dist-packages/laplace/baselaplace.py", line 597, in __call__
    return self.predictive_samples(x, pred_type='glm', n_samples=n_samples,
  File "/usr/local/lib/python3.10/dist-packages/laplace/baselaplace.py", line 660, in predictive_samples
    f_mu, f_var = self._glm_predictive_distribution(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/laplace/baselaplace.py", line 680, in _glm_predictive_distribution
    f_var = self.functional_variance(Js)
  File "/usr/local/lib/python3.10/dist-packages/laplace/baselaplace.py", line 944, in functional_variance
    return self.posterior_precision.inv_square_form(Js)
  File "/usr/local/lib/python3.10/dist-packages/laplace/utils/matrix.py", line 406, in inv_square_form
    SW = self._bmm(W, exponent=-1)
  File "/usr/local/lib/python3.10/dist-packages/laplace/utils/matrix.py", line 396, in _bmm
    W_p = Q1 @ W_p @ Q2.T
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch.